<?php

use Ekv\components\Yii\Db\ActiveRecordBase;
use Ekv\models\MOrderBase;

class BTestOrderBase extends MOrderBase
{
    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }

}
 