<?php

use Ekv\components\Yii\Db\ActiveRecordBase;
use Ekv\models\MOrderBase;
use Ekv\models\MOrderExtra;

class BTestOrderBase extends MOrderBase
{
    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }

    static function getModelByPk($idOrder)
    {
        return static::model()->with(self::REL_ORDER_EXTRAS)->findByPk($idOrder);
    }

    protected function getOrderExtraModelFq()
    {
        return BTestOrderExtra::getClassNameFQ();
    }


}
 